### ISSUE TITLE
Bricked 16S Pro

### ISSUE THREAD

**Issue by Dari1234** [sukanka/MEIZU16S_unlock_tutorial#10]
I want to use QFIL but in the newest Flyme 8.20.1.7 OS there are no prog_firehose_ddr_provision.elf and *.xml files. What to do? 
My 16S Pro is rooted and unlocked and fastboot is working but I'm stucked in a fastboot loop. Flashing recoveries does not help since I end in fastboot mode whatever keys I press.
Using QFIL is my last solution.

**Comment by Dari1234** [comment]
Just a comment - I downloaded the 16s Flyme from Baidu (your link) and have seen that all relevant files are there. Is there a possibility to copy or move the 16S Pro Flyme from TianyiNetdisk to Baidu or Google or somewhere else since I cannot download the data from TianyiNetdisk.

**Comment by sukanka** [comment]
> Just a comment - I downloaded the 16s Flyme from Baidu (your link) and have seen that all relevant files are there. Is there a possibility to copy or move the 16S Pro Flyme from TianyiNetdisk to Baidu or Google or somewhere else since I cannot download the data from TianyiNetdisk.

As you have a copy of the rom, you can upload it to google and paste the link below, I will update it.
To your first question, did you perform a total wipe `fastboot -w` in fastboot after you unlocked your device?

**Comment by sukanka** [comment]
> Just a comment - I downloaded the 16s Flyme from Baidu (your link) and have seen that all relevant files are there. Is there a possibility to copy or move the 16S Pro Flyme from TianyiNetdisk to Baidu or Google or somewhere else since I cannot download the data from TianyiNetdisk.

I've updated a link to BaiduNetdisk.

**Comment by suleymansaglik** [comment]
sukanka... I need urgent help. The meizu 16s was brick. need edl rom. but I can't download edl stock rom because I can't become a baidu member

**Comment by suleymansaglik** [comment]
> > Just a comment - I downloaded the 16s Flyme from Baidu (your link) and have seen that all relevant files are there. Is there a possibility to copy or move the 16S Pro Flyme from TianyiNetdisk to Baidu or Google or somewhere else since I cannot download the data from TianyiNetdisk.
> 
> I've updated a link to BaiduNetdisk.

Can't download edl stock rom for 16s.   can you create another link? eg mailru, drive, mega

**Comment by Dari1234** [comment]
> 
> 
> > Just a comment - I downloaded the 16s Flyme from Baidu (your link) and have seen that all relevant files are there. Is there a possibility to copy or move the 16S Pro Flyme from TianyiNetdisk to Baidu or Google or somewhere else since I cannot download the data from TianyiNetdisk.
> 
> As you have a copy of the rom, you can upload it to google and paste the link below, I will update it.
> To your first question, did you perform a total wipe `fastboot -w` in fastboot after you unlocked your device?

I tried but did not help.

**Comment by Dari1234** [comment]
> 
> 
> > Just a comment - I downloaded the 16s Flyme from Baidu (your link) and have seen that all relevant files are there. Is there a possibility to copy or move the 16S Pro Flyme from TianyiNetdisk to Baidu or Google or somewhere else since I cannot download the data from TianyiNetdisk.
> 
> I've updated a link to BaiduNetdisk.

Thank you very much - you are my hero! Now I can use the phone again!

**Comment by Dari1234** [comment]
> 
> 
> sukanka... I need urgent help. The meizu 16s was brick. need edl rom. but I can't download edl stock rom because I can't become a baidu member

Youtube is your friend - just search for baidu download

**Comment by suleymansaglik** [comment]
> > sukanka... I need urgent help. The meizu 16s was brick. need edl rom. but I can't download edl stock rom because I can't become a baidu member
> 
> Youtube is your friend - just search for baidu download


I have tried EVERY WAY. Not Ind.   :((

**Comment by suleymansaglik** [comment]
PLEASE HELP ME. I CANNOT USE AND OPEN THE DEVICE

**Comment by suleymansaglik** [comment]
> > sukanka ... Acil yardıma ihtiyacım var. Meizu 16s tuğlaydı. edl rom gerekir. ama edl stock rom'u indiremiyorum çünkü bir baidu üyesi olamıyorum
> 
> Youtube arkadaşın - sadece baidu indirmek için arama

friend.  please help me.  but you can succeed.  I need 16s qfil rom.  drive or mail.ru or mega

**Comment by sukanka** [comment]
> > > sukanka ... Acil yardıma ihtiyacım var. Meizu 16s tuğlaydı. edl rom gerekir. ama edl stock rom'u indiremiyorum çünkü bir baidu üyesi olamıyorum
> > 
> > 
> > Youtube arkadaşın - sadece baidu indirmek için arama
> 
> friend. please help me. but you can succeed. I need 16s qfil rom. drive or mail.ru or mega

Sorry, I'm getting trouble with my vps, thus I can't upload the ROMs to my server. And I don't I have enough network flow to upload these ROMs to Gdrive or other drives used in your country either.

Maybe you can ask others to upload the ROMs and share a link here.

**Comment by suleymansaglik** [comment]
I would be very grateful if friends to share.  The device is currently brick.

**Comment by zzeroo** [comment]
what do you need (link please). I can upload and share I think.

**Comment by suleymansaglik** [comment]
> neye ihtiyacınız var (bağlantı lütfen). Sanırım yükleyebilir ve paylaşabilirim.

https://github.com/sukanka/MEIZU16S_unlock_tutorial/wiki/Downgrade-Tutorial

**Comment by suleymansaglik** [comment]
Meizu 16s baidu netdisk . rom qfil. Please . 2 part
Part 1 : 6** mb
Part 2 : 1.5 gb

**Comment by Dari1234** [comment]
have you tried: https://www.youtube.com/watch?v=UgSmx26w6TU

**Comment by suleymansaglik** [comment]
I tried this method.  but unfortunately not.  requests a baidu certificate when downloading.  despite membership

**Comment by Dari1234** [comment]
Strange, because it works for me.
If zzeroo will not upload the files I can do it tomorrow evening

**Comment by suleymansaglik** [comment]
Please.  Thank you very much.  I'm waiting

**Comment by suleymansaglik** [comment]
note: my device is not 16s pro.  mine is 16s

**Comment by Dari1234** [comment]
https://drive.google.com/open?id=11zwIMkZy7imzoUARSZ__acGUcZ9QC5K8
https://drive.google.com/open?id=18ZjW9edsDKd3HhbWXrpX89Nu9o5ttU1s

**Comment by suleymansaglik** [comment]
Thank you very much.  link has arrived.  I started downloading.  you are very good person.  i will pray to god for you

**Comment by Dari1234** [comment]
Did everything work? Is your 16s up and running again?

**Comment by suleymansaglik** [comment]
Yes.  thank you very much.  if we were in the same country.  i would buy you food

**Comment by suleymansaglik** [comment]
Everything is fine for 16s.
