### ISSUE TITLE
提供16T（8+256）的QCN

### ISSUE THREAD

**Issue by Bagener** [sukanka/MEIZU16S_unlock_tutorial#11]
https://drive.google.com/file/d/1jzho9jsus6_PkUXMzIYfG9DvYBiQQLRP/view?usp=sharing

**Comment by sukanka** [comment]
> https://drive.google.com/file/d/1jzho9jsus6_PkUXMzIYfG9DvYBiQQLRP/view?usp=sharing

谢谢,已增加文件
