### ISSUE TITLE
有人遇到16x使用FRP的命令行方式解锁，手机上没有提示吗？

### ISSUE THREAD

**Issue by iwh718** [sukanka/MEIZU16S_unlock_tutorial#12]
直接就返回失败了。

**Comment by sukanka** [comment]
> 直接就返回失败了。
有人说16X不行，你看下16X在recovery里面能不能使用音量键选择各种选项吧，如果不可以，就说明FRP不行。16S是只有两行字，音量键完全不能选择。

**Comment by Cyenoch** [comment]
16x不可用

**Comment by Wobaoziya** [comment]
我的16X也是这样 分区都打不开
[132285660988616454.log](https://github.com/sukanka/MEIZU16S_unlock_tutorial/files/4328820/132285660988616454.log)
