### ISSUE TITLE
For Lenovo A5

### ISSUE THREAD

**Issue by Demigoddd** [sukanka/MEIZU16S_unlock_tutorial#16]
Thanks for the new way to unlock the bootloader for Meizu.
https://github.com/sukanka/MEIZU16S_unlock_tutorial/wiki/FRP-Method

I tried this method for my Lenovo, but to no avail.
I think Lenovo may be a different address? (`0007fff0f`)

I would be glad if someone helps to figure out how to unlock my Lenovo A5 L18021.
Thanks

**Comment by sukanka** [comment]
> Thanks for the new way to unlock the bootloader for Meizu.
> https://github.com/sukanka/MEIZU16S_unlock_tutorial/wiki/FRP-Method
> 
> I tried this method for my Lenovo, but to no avail.
> I think Lenovo may be a different address? (`0007fff0f`)
> [frp.zip](https://github.com/sukanka/MEIZU16S_unlock_tutorial/files/4422381/frp.zip)
> 
> I would be glad if someone helps to figure out how to unlock my Lenovo A5 L18021.
> Thanks

did you see this? https://forums.lenovo.com/t5/A5-L18021-Smartphones/A5-L18021-Bootloader-Cannot-Become-Unlocked/m-p/4378677
BTW, this repo is for meizu devices only. the frp method does not work on Lenovo devices as you can apply for an unlock code on lenovo's official site.
