### ISSUE TITLE
魅族16s Pro 8+128 QCN 备份分享

### ISSUE THREAD

**Issue by kcn3388** [sukanka/MEIZU16S_unlock_tutorial#18]
本人备份的QCN，希望可以帮到大家，另外感谢教程作者提供的教程。

因为GitHub上传限制，将其打包在zip文件里了。
[16sPro_8128_001.zip](https://github.com/sukanka/MEIZU16S_unlock_tutorial/files/4493796/16sPro_8128_001.zip)

**Comment by sukanka** [comment]
感谢分享，已经提交到`qcn-backup` 分支

**Comment by iamkrava89** [comment]
THANKS!!!!!! You have saved my phone!
Successfully restored QCN, edited to my IMEIs and MEID!
kcn3388 you are the best. Forgot to made a backup and bricked my network setting.
You have helped me so much!

**Comment by kcn3388** [comment]
> THANKS!!!!!! You have saved my phone!
> Successfully restored QCN, edited to my IMEIs and MEID!
> kcn3388 you are the best. Forgot to made a backup and bricked my network setting.
> You have helped me so much!

You're welcome. Glad to help you.
