### ISSUE TITLE
Flashing Flyme via TWRP

### ISSUE THREAD

**Issue by vittoriosantagiuliana** [sukanka/MEIZU16S_unlock_tutorial#24]
Hi, I wonder whether it is possible to install Flyme using TWRP recovery, so I can flash magisk & modules.
In particular I'd like to know if installing Flyme:
- Flyme locks the bootloader?
- Flyme removes TWRP?
- Do I have to patch update.zip before installing it?

**Comment by sukanka** [comment]
Surely you can.
Here are the steps:
1. Flash update.zip (full ver, over 2GB generally)
2. Flash magisk to prevent TWRP being overridden.
3. Reboot.
This will not relock bootloader.
