### ISSUE TITLE
已上车，说点该注意的东西

### ISSUE THREAD

**Issue by cy745** [sukanka/MEIZU16S_unlock_tutorial#3]
按照wiki里的内容做是完全ok的，我就是用28号最新的内测版来解的；
所以内测还是稳定版都不会有之前旧方法时出现的问题；
只有一点需要注意，解锁完bl后，尝试重启进入系统是进不了的，会出现文字正在准备系统啥的而且没有转圈圈的进度条提示，就这样卡了一之后会自动进入原版的r会ec；
（这里的清除数据好像只能用原版rec来清，用twrp的无效果）
在这里**按五下音量上，再按五下音量下**，就会出现清除数据的选项；
选择清除，确认，然后就可以进系统了；
但原来的东西肯定也是没有的了（注意备份自己的重要文件），这之后再刷twrp；
------------------------------------------------------------------------------------
16s的bl解了，但又不知道有什么好玩的，有没有什么可以推荐啊？

**Comment by sukanka** [comment]
这个注意事项我写了的，现在又标记了加粗。
> **建议解锁之后按照降级教程刷一遍，或者重启进入 Recovery(可能要等比较久), 在 Recovery 按5次音量上,5次音量下,彻底清除一次数据.** 不然可能会出现各种各样的问题,比如不能开机、在Recovey 不能触屏。

解锁之后去尝试各种Magisk 模块吧，我主要是用存储重定向、现在还有 QuickSwitch(我不会用）。
我觉得解锁最方便的其实是有了TWRP，如果刷了某个模块不开机，可以直接在Recovery 里面删除。

> ## 按照wiki里的内容做是完全ok的，我就是用28号最新的内测版来解的；
> 所以内测还是稳定版都不会有之前旧方法时出现的问题；
> 只有一点需要注意，解锁完bl后，尝试重启进入系统是进不了的，会出现文字正在准备系统啥的而且没有转圈圈的进度条提示，就这样卡了一之后会自动进入原版的r会ec；
> （这里的清除数据好像只能用原版rec来清，用twrp的无效果）
> 在这里**按五下音量上，再按五下音量下**，就会出现清除数据的选项；
> 选择清除，确认，然后就可以进系统了；
> 但原来的东西肯定也是没有的了（注意备份自己的重要文件），这之后再刷twrp；
> 16s的bl解了，但又不知道有什么好玩的，有没有什么可以推荐啊？
