### ISSUE TITLE
16xs有线刷包吗

### ISSUE THREAD

**Issue by xesp** [sukanka/MEIZU16S_unlock_tutorial#7]
16xs真心不属于16系呀。现在还没有线刷包。
看到新方法，想尝试，但没有线刷包呀。。。可咋整

**Comment by sukanka** [comment]
> 16xs真心不属于16系呀。现在还没有线刷包。
> 看到新方法，想尝试，但没有线刷包呀。。。可咋整

我没有16xs 的线刷包,不然肯定就放出来了,也没有看到别人分享的16xs 的线刷包 #

**Comment by xesp** [comment]
这个要怎么提取？现在16xs官网就一个8.0的包，再没了。有一个7.0的也没用，不能降级刷，上次就搞的去了回售后。
这个机器是不是买的太小众了。现在ROOT的也不完全，弄个微信天天闪退，一直没有大佬分享一下高端技术，看来不行还得回归太极呀。

**Comment by sukanka** [comment]
> 这个要怎么提取？现在16xs官网就一个8.0的包，再没了。有一个7.0的也没用，不能降级刷，上次就搞的去了回售后。
> 这个机器是不是买的太小众了。现在ROOT的也不完全，弄个微信天天闪退，一直没有大佬分享一下高端技术，看来不行还得回归太极呀。

线刷包要从魅族服务器或者售后处提取。线刷包和普通的升级包不一样的。另外Root 不完全可以解锁获取完整Root啊

**Comment by xesp** [comment]
用fastboot的那个呗。解开BL然后刷面具呗。那么如果黑了，是不是没得线刷包只能去售后呀。
没准备好，心里还是有些胆怯呀。

**Comment by sukanka** [comment]
> 16xs真心不属于16系呀。现在还没有线刷包。
> 看到新方法，想尝试，但没有线刷包呀。。。可咋整

已更新16xs线刷包
