### ISSUE TITLE
关于开机报错和微信指纹

### ISSUE THREAD

**Issue by Kissycat** [sukanka/MEIZU16S_unlock_tutorial#8]
解锁之后，开机会报错，提示系统内部存在问题，然后微信指纹也会用不了，大家有解决的思路嘛..

**Comment by sukanka** [comment]
> 解锁之后，开机会报错，提示系统内部存在问题，然后微信指纹也会用不了，大家有解决的思路嘛..

开机报错我没遇到过，但是有其他人遇到过，你需要提供更详细的信息，包括机型，版本，错误的截图。
至于微信指纹用不了是微信的问题，可以使用magisk模块解决(伪指纹)

**Comment by Kissycat** [comment]
> > 解锁之后，开机会报错，提示系统内部存在问题，然后微信指纹也会用不了，大家有解决的思路嘛..
> 
> 开机报错我没遇到过，但是有其他人遇到过，你需要提供更详细的信息，包括机型，版本，错误的截图。
> 至于微信指纹用不了是微信的问题，可以使用magisk模块解决(伪指纹)

啊，微信那个模块用着实在有点逼死强迫症的感觉，我在用最新一月三号的内测（flyme8.20.1.2daily），16th Plus....
![S00104-12405094](https://user-images.githubusercontent.com/20614068/71759889-90d28a80-2eef-11ea-8fd9-618a84ef6d3c.png)
![S00104-12352946](https://user-images.githubusercontent.com/20614068/71759891-96c86b80-2eef-11ea-9c1b-bcda0b57d70a.png)
![S00104-09152321](https://user-images.githubusercontent.com/20614068/71759893-a0ea6a00-2eef-11ea-8337-2254d7896f9c.png)
![S00103-23265458](https://user-images.githubusercontent.com/20614068/71759895-a5af1e00-2eef-11ea-8044-0bc868fa68cb.png)
